In [10]:
import torch
import numpy as np

---

### Creating Tensors

In [11]:
### Creating TENSORS
### Tensors are multi-dimensional arrays.
### They are almost identical to numpy.ndarray. but they can run on GPU

# From List
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
display(x_data)

# Random values
shape = (2, 3,)
rand_tensor = torch.rand(shape)
display(rand_tensor)

# Tensors of zeros and ones
zeros_tensor = torch.zeros(shape)
ones_tensor = torch.ones(shape)
display(zeros_tensor)
display(ones_tensor)

# From NumPy Array
np_array = np.array([1, 2, 3])
t2 = torch.from_numpy(np_array)
display(t2)

tensor([[1, 2],
        [3, 4]])

tensor([[0.8340, 0.3793, 0.3039],
        [0.3907, 0.6460, 0.2960]])

tensor([[0., 0., 0.],
        [0., 0., 0.]])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor([1, 2, 3])

---

### Tensor Attributes

In [7]:
### Tensor Attributes
### Every tensor has 3 key properties:
### shape: Dimension of the tensor
### dtype: Datatype of the tensor
### device: Where the tensor lives

tensor = torch.rand(3, 4)
print(f"Shape of the tensor: {tensor.shape}")
print(f"Datatype of the tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of the tensor: torch.Size([3, 4])
Datatype of the tensor: torch.float32
Device tensor is stored on: cpu


---

### Tensor Operations

In [14]:
### Basic Operations
### WE can perform normal math like standard NumPy

A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])

### Element wise operations
add_res = A + B
sub_res = A - B
mul_res = A * B ## This is not dot product. This is element wise multiplication
div_res = A / B

print(f"Element-wise Addition:\n{add_res}")
print(f"Element-wise Subtraction:\n{sub_res}")
print(f"Element-wise Multiplication:\n{mul_res}")
print(f"Element-wise Division:\n{div_res}")

A.add_(10)
print(f"In-Place Addition Results:\n{A}")

Element-wise Addition:
tensor([[ 6,  8],
        [10, 12]])
Element-wise Subtraction:
tensor([[-4, -4],
        [-4, -4]])
Element-wise Multiplication:
tensor([[ 5, 12],
        [21, 32]])
Element-wise Division:
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
In-Place Addition Results:
tensor([[11, 12],
        [13, 14]])


### Matrix Multiplication

In [ ]:
### Matrix Multuplication
tensor_a = torch.tensor([[1, 2], 
                         [3, 4]])

tensor_b = torch.tensor([[5, 6], 
                         [7, 8]])

# Using @ operator
result1 = tensor_a @ tensor_b

# Using torch.matmul()
result2 = torch.matmul(tensor_a, tensor_b)

# Using torch.mm(), but only for 2D Matrix
# torch.matmul() is much more flexible
result3 = torch.mm(tensor_a, tensor_b)

print(f"Matrix Multiplication Results:\n{result2}")

Matrix Multiplication Results:
tensor([[19, 22],
        [43, 50]])


### **Concept**: Matrix Transpose

In [20]:
tensor_3x2 = torch.rand(3, 2)
tensor_3x2_again = torch.rand(3, 2)

# torch.matmul(tensor_3x2, tensor_3x2_again)

### Concept: We often transpose the matrix to make the matrix eligible for dot product
fixed_result = torch.matmul(tensor_3x2, tensor_3x2_again.T)
print(f"Final Result Shape: {fixed_result.shape}")
print(f"Result:\n{fixed_result}")


Final Result Shape: torch.Size([3, 3])
Result:
tensor([[0.2748, 0.5669, 0.3683],
        [0.4409, 0.1814, 0.2084],
        [0.3166, 0.7202, 0.4596]])


---

### Reshaping and Viewing

In [22]:
### Reshaping and Viewing

### In Deep Learning, you often need to change the "shape" of data without 
### changing the actual numbers inside. For example, flattening a
### 28×28 image into a single 784-length vector.

In [ ]:
### view(): Extremely fast but tensor must be contiguous in the memory.
### STANDARD IN PYTORCH

### reshape(): Similar to view but handles non-contiguous data

x = torch.arange(1, 10) # Creates [1, 2, 3, 4, 5, 6, 7, 8, 9]

### Reshaping to 3x3
x_3x3 = x.view(3, 3)
print(f"Reshaped to 3x3:\n{x_3x3}")

### Flatten back to 1D
### -1 tels PyTorch: "Ca;cu;ate this dimension automatically based on the others"
x_flattened = x_3x3.view(-1) 
print(f"Flattened tensor:\n{x_flattened}") # torch.Size([9])

Reshaped to 3x3:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Flattened tensor:
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


### Squeezing and Unsqueezing

In [29]:
### Squeeze and Unsqueeze
### Unsqueeze: Adds a dimension
### Squeeze: Removes all dimensions of size 1

x = torch.zeros(10)

### Adding a dimension at index 0
x_unsqueezed = x.unsqueeze(dim=0)
x_unsqueezed = x_unsqueezed.unsqueeze(dim=2)
print(f"Unsqueezed Shape: {x_unsqueezed.shape}")
print(f"Tensor:\n{x_unsqueezed}")

### Remove the dimension
x_squeezed = x_unsqueezed.squeeze()
print(f"Squeezed Shape: {x_squeezed.shape}")

Unsqueezed Shape: torch.Size([1, 10, 1])
Tensor:
tensor([[[0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.]]])
Squeezed Shape: torch.Size([10])


---

### Broadcasting

In [33]:
### Broadcasting:
### Using broadcasting, we can apply operating between tensors 
### provided that they follow some criteria

### Rules of Broadcasting:
### 1. The dimensions are equal
### 2. One of the dimensions is 1.

### Scalar Broadcasting
x = torch.tensor([1, 2, 3])
print(x + 10)

### Vector to Matrix Broadcasting
A = torch.ones((3, 3))
b = torch.tensor([1, 2, 3])
result = A + b
print(f"Matrix A:\n{A}")
print(f"Vector b:\n{b}")
print(f"Result (b added to every row of A):\n{result}")

c = torch.tensor([10, 20, 30]).unsqueeze(dim=1)
result_col = A + c
print(f"Result (c added to every column of A):\n{result_col}")

tensor([11, 12, 13])
Matrix A:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Vector b:
tensor([1, 2, 3])
Result (b added to every row of A):
tensor([[2., 3., 4.],
        [2., 3., 4.],
        [2., 3., 4.]])
Result (c added to every column of A):
tensor([[11., 11., 11.],
        [21., 21., 21.],
        [31., 31., 31.]])


---

### Indexing and Slicing

In [ ]:
### Indexing and Slicing

### Syntax
### tensor[start:end(excluded):step]
### tensor[dim0, dim1, dim2]
x = torch.tensor([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])

print(f"Single Element: {x[1, 1]}")
print(f"First row: {x[0,:]}")
print(f"Third column: {x[:,2]}")
print(f"Sub-Matrix:\n{x[0:2, 0:2]}")

Single Element: 5
First row: tensor([1, 2, 3])
Third column: tensor([3, 6, 9])
Sub-Matrix:
tensor([[1, 2],
        [4, 5]])


### Boolean Slicing

In [44]:
### Boolean Indexing
x = torch.tensor([1, 10, 2, 20, 3, 30])
mask = x > 5
print(f"Values > 5: {x[mask]}")

Values > 5: tensor([10, 20, 30])


---